// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROGRESSMSG_CPU_MONITOR_MSG_H_
#define FLATBUFFERS_GENERATED_PROGRESSMSG_CPU_MONITOR_MSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 29,
             "Non-compatible flatbuffers version included");

namespace cpu_monitor {
namespace msg {

struct ThreadInfo;
struct ThreadInfoBuilder;

struct ProgressInfo;
struct ProgressInfoBuilder;

struct ProgressMsg;
struct ProgressMsgBuilder;

struct ThreadInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ThreadInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_USAGE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  float usage() const {
    return GetField<float>(VT_USAGE, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_USAGE, 4) &&
           verifier.EndTable();
  }
};

struct ThreadInfoBuilder {
  typedef ThreadInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(ThreadInfo::VT_NAME, name);
  }
  void add_usage(float usage) {
    fbb_.AddElement<float>(ThreadInfo::VT_USAGE, usage, 0.0f);
  }
  explicit ThreadInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ThreadInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ThreadInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<ThreadInfo> CreateThreadInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    float usage = 0.0f) {
  ThreadInfoBuilder builder_(_fbb);
  builder_.add_usage(usage);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<ThreadInfo> CreateThreadInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float usage = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return cpu_monitor::msg::CreateThreadInfo(
      _fbb,
      name__,
      usage);
}

struct ProgressInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ProgressInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_INFOS = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>> *infos() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>> *>(VT_INFOS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_INFOS) &&
           verifier.VerifyVector(infos()) &&
           verifier.VerifyVectorOfTables(infos()) &&
           verifier.EndTable();
  }
};

struct ProgressInfoBuilder {
  typedef ProgressInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(ProgressInfo::VT_NAME, name);
  }
  void add_infos(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>>> infos) {
    fbb_.AddOffset(ProgressInfo::VT_INFOS, infos);
  }
  explicit ProgressInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ProgressInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ProgressInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<ProgressInfo> CreateProgressInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>>> infos = 0) {
  ProgressInfoBuilder builder_(_fbb);
  builder_.add_infos(infos);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<ProgressInfo> CreateProgressInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>> *infos = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto infos__ = infos ? _fbb.CreateVector<flatbuffers::Offset<cpu_monitor::msg::ThreadInfo>>(*infos) : 0;
  return cpu_monitor::msg::CreateProgressInfo(
      _fbb,
      name__,
      infos__);
}

struct ProgressMsg FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ProgressMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INFOS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>> *infos() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>> *>(VT_INFOS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INFOS) &&
           verifier.VerifyVector(infos()) &&
           verifier.VerifyVectorOfTables(infos()) &&
           verifier.EndTable();
  }
};

struct ProgressMsgBuilder {
  typedef ProgressMsg Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_infos(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>>> infos) {
    fbb_.AddOffset(ProgressMsg::VT_INFOS, infos);
  }
  explicit ProgressMsgBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ProgressMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ProgressMsg>(end);
    return o;
  }
};

inline flatbuffers::Offset<ProgressMsg> CreateProgressMsg(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>>> infos = 0) {
  ProgressMsgBuilder builder_(_fbb);
  builder_.add_infos(infos);
  return builder_.Finish();
}

inline flatbuffers::Offset<ProgressMsg> CreateProgressMsgDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>> *infos = nullptr) {
  auto infos__ = infos ? _fbb.CreateVector<flatbuffers::Offset<cpu_monitor::msg::ProgressInfo>>(*infos) : 0;
  return cpu_monitor::msg::CreateProgressMsg(
      _fbb,
      infos__);
}

inline const cpu_monitor::msg::ProgressMsg *GetProgressMsg(const void *buf) {
  return flatbuffers::GetRoot<cpu_monitor::msg::ProgressMsg>(buf);
}

inline const cpu_monitor::msg::ProgressMsg *GetSizePrefixedProgressMsg(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<cpu_monitor::msg::ProgressMsg>(buf);
}

inline bool VerifyProgressMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<cpu_monitor::msg::ProgressMsg>(nullptr);
}

inline bool VerifySizePrefixedProgressMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<cpu_monitor::msg::ProgressMsg>(nullptr);
}

inline void FinishProgressMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<cpu_monitor::msg::ProgressMsg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedProgressMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<cpu_monitor::msg::ProgressMsg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace msg
}  // namespace cpu_monitor

#endif  // FLATBUFFERS_GENERATED_PROGRESSMSG_CPU_MONITOR_MSG_H_
