name: cpu_monitor

on:
  push:
    paths-ignore:
      - '**.md'
      - 'ui/**'
      - 'ui-tauri/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'ui/**'
      - 'ui-tauri/**'

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf
          sudo apt-get install -y g++-arm-linux-gnueabihf

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CMake Build
        run: |
          mkdir build_x86 && cd build_x86
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_UI=OFF -DCMAKE_EXE_LINKER_FLAGS="-static -s"
          make cpu_monitor -j2
          mv daemon/cpu_monitor cpu_monitor
          zip -r cpu_monitor_x86.zip cpu_monitor
          cd ..
          mkdir build_arm && cd build_arm
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_UI=OFF -DCMAKE_EXE_LINKER_FLAGS="-static -s" -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++
          make cpu_monitor -j2
          mv daemon/cpu_monitor cpu_monitor
          zip -r cpu_monitor_arm.zip cpu_monitor

      - name: Archive X86
        uses: actions/upload-artifact@v3
        with:
          name: cpu_monitor_x86_${{ runner.os }}_${{ github.sha }}
          path: build_x86/cpu_monitor_x86.zip

      - name: Archive ARM
        uses: actions/upload-artifact@v3
        with:
          name: cpu_monitor_arm_${{ runner.os }}_${{ github.sha }}
          path: build_arm/cpu_monitor_arm.zip

      - name: Release X86
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_x86/cpu_monitor_x86.zip
          asset_name: cpu_monitor_x86.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Release ARM
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_arm/cpu_monitor_arm.zip
          asset_name: cpu_monitor_arm.zip
          tag: ${{ github.ref }}
          overwrite: true
