name: macOS

on:
  push:
    paths-ignore:
      - '**.md'
      - 'daemon/**'
      - 'ui-tauri/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'daemon/**'
      - 'ui-tauri/**'

jobs:
  macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CMake Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make CpuMonitor cpu_monitor -j2
          mv ui/CpuMonitor.app CpuMonitor.app
          mv daemon/cpu_monitor cpu_monitor
          zip -r CpuMonitor.zip CpuMonitor.app
          zip -r cpu_monitor.zip cpu_monitor

      - name: Archive UI
        uses: actions/upload-artifact@v3
        with:
          name: CpuMonitor_${{ runner.os }}_${{ github.sha }}
          path: build/CpuMonitor.zip

      - name: Archive Daemon
        uses: actions/upload-artifact@v3
        with:
          name: cpu_monitor_${{ runner.os }}_${{ github.sha }}
          path: build/cpu_monitor.zip

      - name: Release UI
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/CpuMonitor.zip
          asset_name: CpuMonitor_${{ runner.os }}.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Release Daemon
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cpu_monitor.zip
          asset_name: cpu_monitor_${{ runner.os }}.zip
          tag: ${{ github.ref }}
          overwrite: true
